---
sudo: required
language: python
dist: trusty
services:
  - docker
before_install:
  - sudo apt-get update
#  - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-engine
install:
  - deactivate
  - pip install ansible ansible-lint molecule docker
script:
  - molecule --debug test
# notifications:
#   slack:
#     rooms:
#       - secure: "something"
#     on_success: always
#   webhooks: https://galaxy.ansible.com/api/v1/notifications/
