sudo: required
language: python
services:
  - docker
before_install:
  - sudo apt-get update
#  - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-engine
install:
  - pip install molecule
  - pip install docker-py
  - pip install ansible-lint
script:
  - molecule test
