---
- name: Check for Supported System
  assert:
    that:
      - (ansible_os_family == 'Amazon' and ansible_distribution_version >= '2017.03') or
        (ansible_distribution == 'CentOS' and ansible_distribution_major_version == '7') or
        (ansible_distribution == 'Ubuntu' and ansible_distribution_version == '16.04')
    msg: "{{ ansible_distribution }} {{ ansible_distribution_version }} is not supported."
