---
dependency:
  name: galaxy
driver:
  name: docker
lint:
  name: yamllint
platforms:
  - name: amazonlinux
    image: amazonlinux
    image_version: 2017.03.0.20170401
  - name: centos-7
    image: centos
    image_version: 7
  - name: ubuntu-16_04
    image: ubuntu
    image_version: 16.04
provisioner:
  name: ansible
  lint:
    name: ansible-lint
scenario:
  name: default
  test_sequence:
    - destroy
    - dependency
    - syntax
    - lint
    - create
    - converge
    - idempotence
    - check
    - verify
    - destroy
verifier:
  name: testinfra
  lint:
    name: flake8
